language: python
before_install:
  - node --version
  - npm link --python=python2 ./__dredd__
  - bundle install

python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

script:
  - python -B -m unittest discover
  - pip install -e .
  - bundle exec cucumber
