language: perl
before_install:
    - npm link --python=python2 ./__dredd__
    - bundle install
script:
    - perl Build.PL && ./Build build && ./Build test
    - ./Build install
    - bundle exec cucumber
perl:
  - "5.18"
  - "5.20"
  - "5.22"
